language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-django 
  - pip install django-rest-framework
  - pip install codecov

install:
  - pip install ".[test]" .

script: pytest

after_success:
  - codecov # submit coverage
